CREATE TABLE IF NOT EXISTS simulation_results (
    id BIGSERIAL PRIMARY KEY,
    snr_db TEXT,
    ber_theoretical TEXT,
    ber_simulated TEXT,
    modulation_type VARCHAR(20),
    code_rate NUMERIC(5,2),
    snr_min NUMERIC(5,2),
    snr_max NUMERIC(5,2),
    simulation_time_ms INTEGER,
    simulation_type VARCHAR(50) DEFAULT 'BER_SNR',
    beam_angles TEXT,
    beam_pattern_db TEXT,
    steering_angle NUMERIC(6,2),
    num_antennas INTEGER,
    frequency_ghz NUMERIC(6,2),
    main_lobe_width NUMERIC(6,2),
    side_lobe_level NUMERIC(6,2),
    bpsk_ber TEXT,
    qpsk_ber TEXT,
    qam16_ber TEXT,
    qam64_ber TEXT,
    comparison_snr_min NUMERIC(6,2),
    comparison_snr_max NUMERIC(6,2),
    crossover_points TEXT,
    num_ofdm_symbols INTEGER,
    capacity_curves_json TEXT,
    spectral_efficiency_json TEXT,
    insights_json TEXT,
    fft_size INTEGER,
    hardware_used VARCHAR(255),
    timestamp TIMESTAMP,
    duration_ms BIGINT,
    compute_type VARCHAR(255),
    memory_mb DOUBLE PRECISION,
    sionna_version VARCHAR(255),
    note TEXT,
    starred BOOLEAN DEFAULT FALSE,
    experiment_id BIGINT,
    share_token VARCHAR(255) UNIQUE,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    colormap_used VARCHAR(50)
);
